namespace: ledger-app-prod
app:
  name: ledger-app-prod
  domain: zekibalci.com
web:
  name: ledger-app-web-prod
  image: hub.zekibalci.com:5000/ledger-app-web-prod:91
  containerPort: 8081
  replicaCount: 2
sql:
  name: ledger-app-sql-prod
  image: hub.zekibalci.com:5000/ledger-app-sql-prod:latest
  containerPort: 3306
  replicaCount: 1